### ISSUE TITLE
 Why EVOPS website is ERR_CONNECTION_RESET.

### ISSUE THREAD

**Issue by luoshunli** [prime-slam/evops-page#5]
Hi, I can not to open the website.  Can you help me?  Thanks

**Comment by pmokeev** [comment]
@luoshunli Hello! It seems that website is working and I cannot reproduce `ERR_CONNECTION_RESET` issue. Can you try it now and let me know, is everything OK?
![image](https://github.com/prime-slam/evops-page/assets/75482510/43340561-6364-462a-9807-adf50d9a5f34)
